# First Python file (Click on the "Markdown" from "Code")
## Second (type "#" for first line , "##" for 2nd line, "###" 3rd line )
### Third

# First Python Program

## This will output as it is

In [1]:
# This is a single line comment. 
print("Before comment") 
# This is second comment
print("After Comment")


Before comment
After Comment


In [2]:
print("Before multi line comment")
''' 
This can be used as multi line comment.
It is used to comment multiple lines of codes
'''
print("After comment")

Before multi line comment
After comment


In [5]:
print(-123.5)
print("Hello everyone")

-123.5
Hello everyone


In [6]:
print(5)

5


In [7]:
print(True)

True


In [8]:
# Text is always inclosed in inverted commas.
print("welcome to python")

welcome to python


## Data Types

In [ ]:
print("There are 4 different data types in Python - Float, Integer(int), String(str), Boolean")

In [37]:
print(type(24.5), type(24), type(True), type("24.5"))

<class 'float'> <class 'int'> <class 'bool'> <class 'str'>


In [34]:
# Type-casting
int(24.5)

24

In [14]:
float(24)

24.0

In [15]:
str(23)
int(10.9)

10

In [18]:
type(True)

bool

In [20]:
int(True)

1

# Expressions and Variables

In [21]:
print(55/11)

5.0


In [22]:
print(55-5)
50+5

50


55

In [23]:
print(55*5)

275


In [24]:
# use '//' for integer value of division
print(55//10)

5


In [25]:
print(4**3)

64


In [26]:

print(20**2)
print(20**3)
20*5

400
8000


100

In [43]:
x = 20
print(x**2)
print(x**3)
x*5

400
8000


100

In [ ]:
print(x+5)

In [29]:
x_bool = True
print(int(x_bool))
age_tom = 0

1


In [31]:
num1 = 5
num2 = num1*2
print(num1, num2)

5 10


In [30]:
x

NameError: name 'x' is not defined

In [ ]:
print("x")
print(x)
x_string = "First String_Variable"
print(x_string)

In [38]:
# Using veriable within other variable
a = 13
b = 15
summation = a + b
summation

28

In [40]:
n = 5

In [ ]:
print(n)

In [44]:
print("n")
print('This is the pointed value by n', n, x)

n
This is the pointed value by n 5 20


In [ ]:
a = x
print(a)
print(x)

In [ ]:
x = 10
print("X = ", x)
print("a = ", a)

In [ ]:
# Order of operations
x = 2
y = 1 + x * (2 / 2) 
y

# Knowledge check

In [49]:
#write a program to swap the vaues of the variables: a=4, b=9
a = 7
b = 9
a=b
a=a

print(b)
print(a)

9
9


In [54]:
#write a program to swap the vaues of the variables: a=4, b=9
a = 10
b = 9

temp = a # taking the value of above
a=b
b=temp

print(b)
print(a)

10
9


# String Operations

In [55]:
print("Strings are array of characters, special symbol, numbers or combination")

Strings are array of characters, special symbol, numbers or combination


In [56]:
message = "Welcome to Python"
print(message)

Welcome to Python


In [62]:
message[5]

'm'

In [61]:
N_V= message[-12]
N_V

'm'

In [ ]:
message

In [ ]:
message[-9]

In [63]:
# String Slicing
message[0:6]

'Welcom'

In [64]:
message[2:5]

'lco'

In [71]:
print(message[12:17 ])
print(message[12: ])
x= 17
print(message[12:x])
print(message[12: 6])
print(message[-5:     ])
print(message[   :3])

ython
ython
ython

ython
Wel


In [76]:
print("this is inverted comma .")

this is inverted comma .


In [80]:
print("this is example of usage of escape \" character. Similarly to enter new line use: \n This will be a new line")
print("this is new \"\"line")

this is example of usage of escape " character. Similarly to enter new line use: 
 This will be a new line
this is new ""line


In [82]:
# str print in new line - [new line use: \n This will be a new line"]
print("this is example of usage of escape \" character. Similarly to enter new line use: \n This will be a new line")


this is example of usage of escape " character. Similarly to enter new line use: 
 This will be a new line


In [83]:
message.upper()

'WELCOME TO PYTHON'

In [ ]:
message.lower()

In [ ]:
len(message)

# Knowledge check

In [85]:
# Write a program to display the message " Welcome Firstname Lastname". Firstname and Lastname are two string variables
Firstname = "Tom"
Lastname = "Hanks"


In [87]:
print("Welcome",Firstname, Lastname)

Welcome Tom Hanks


In [95]:
# Write a program to display the string repeat_text n number of times. n is integer variable.
n = 7
repeat_text = "Hurray "
print(repeat_text * n)
# sample output = Hurray Hurray Hurray Hurray


Hurray Hurray Hurray Hurray Hurray Hurray Hurray 


In [99]:
var_x = 0
var_x = var_x + 5
var_x

5

# Functions

# Function

In [ ]:
def 

In [3]:
print('begening function')
def addition():
    x = 1
    y = 2
    z = x + y
    print(z)
    print(x,y)    
    print("inside function")
    
print("outside function")


begening function
outside function


In [6]:
addition()
x = 1
y = 2
z = x + y
print(z)

3
1 2
inside function
3


In [9]:
#print(addition())
x= 9
y =16
print(x,y)
#print(addition())
#addition()

9 16


In [ ]:
print("test")
addition()
print("after test")


In [ ]:
printaddition()

In [10]:
def addition(x,y):
    print("x =",x)
    print("y=",y)
    z = x + y
    print("message")
    print(z)

In [14]:
addition(5, -11)

x = 5
y= -11
message
-6


In [12]:
#addition(2,3)
addition(5, -11)
x = "Global Variable"
def simple_in(prin, intrest, period):
    x_in_local = 10
    si = (prin * intrest * period )/100
    print(x_in_si)
    print(si)

x = 5
y= -11
message
-6


In [ ]:
print(x)

In [ ]:
simple_in(1000, 2, 4)

In [ ]:
si = 10
print(si)
simple_in(1000, 2, 4)
print(si)

In [17]:
def addition(x,y):
    z = x + y
    x =10
    y =20
    return z, x, y 
    print('inside')

In [ ]:
answer, x, y = addition(7,9)
print(answer, x, y)

# Knowledge check

In [ ]:
# Write a function to return the cube of number

number = 12



# Tuple, List, Dictionary, Set

In [ ]:
# Tuple
x = (1,2,"Mike", "Adam",12.5)
print(x)

In [ ]:
x =9
x

In [ ]:
len(x)

In [ ]:
y = x[1] * 3
y
x

In [ ]:
x[3]

In [ ]:
x[1:3]

In [ ]:
# tuples are immutable
x[0]=5

In [ ]:
y = x + (2,3)
print(y)

In [ ]:
# Strings are also immuatble
message = "welcome"
message[2] = "o"


In [ ]:
# List
list_x = ['abc', 1,2,5.4,7,4,7]
list_x

In [ ]:
# Lists are similar to tuples but are mutable
x  = ('abc', 1,2,5.4, 7,4,7)
y =['abc', 1,2,5.4,7,4,7]
y

In [ ]:
x[0] = 4.5

In [ ]:
y[0] = 4.5
y
x[0]

In [ ]:
print(y)
z = y
print(z)

In [ ]:
z[0]="abc"
z

In [ ]:
y

In [ ]:
y.extend([7,1])
y

In [ ]:
del(y[2])
y

In [ ]:
#y.remove(7)
y

In [ ]:
z= [1,3, 7] + y +[0,2]
z

In [ ]:
nested_z = [1, 3,5, [8, 'abc', 'pqr' ], 9,9, "temp", 10.5]
nested_z

In [20]:
# sets are collection
set_x = {1, 4, "y", 4, 3.5 ,8}
set_x
set_x{1}

SyntaxError: invalid syntax (<ipython-input-20-b14503490486>, line 4)

In [ ]:
y = [3,5,7,6,3,3,"abc"]
print(type(y))
print(y)

In [ ]:
float(8)

In [ ]:
sety = set(y)
sety

In [ ]:
y

In [ ]:
sety.add(8)
sety

In [ ]:
sety.remove(7)
sety

In [ ]:
setz={"a","v","d",1,3}
setz.union(sety)

In [ ]:
setz & sety

In [ ]:
sety[0]

In [ ]:
#Dictionaries are collection of key value pair
dict_x = {"one":"abc", "two":1, "three":4.5 , 2: 9.0, "two_1": 1}
dict_x

In [ ]:
print(y)
print(y[4])
dict_x[2]

In [ ]:
# add new key value to dictionary
dict_x["four"] = 5.6
dict_x

In [ ]:
# add new key value to dictionary
dict_x["three"] = 8
dict_x

In [ ]:
dict_x["one"] = "xyz"
dict_x

In [ ]:
print(dict_x.keys())

In [ ]:
print(dict_x.values())

In [ ]:
"two" in dict_x

In [ ]:
"five" in dict_x

In [ ]:
del(dict_x["three"])
dict_x

In [ ]:
print(y)
dict_x["third"] = y
dict_x

In [ ]:
dict_x["third"]

In [ ]:
dict_x["third"][1:4]

In [ ]:
len(dict_x)

In [ ]:
dict_x["five"] = "one"
dict_x['six'] = 'one'
dict_x

# List, Set, Dictionary are mutable while Float, Int, Bool, Str, Tuple are immutable

In [ ]:
# Write one line code to count number of distinct values in the list: x=[1,3,4,2,6,1,4,8,4,2]
x=[1,3,4,2,6,1,4,8,4,2]


# Comparison operators

In [ ]:
x = 1
x == 2

In [ ]:
2 > 3

In [ ]:
2 < 3

In [ ]:
5 <= 4

In [ ]:
2 == 3

In [ ]:
2==2

In [ ]:
2 != 3

In [ ]:
2 = 3

In [ ]:
x = 50 

if x < 60:
    print("x is less than 5. B Grade")
    print("in if")
    
    print("still in if")
print("outside if")

In [21]:
x = 6
if x > 5:
    print("In if")
    
# check    
    
    
    print("x is greater than 5")
else:
    print("In else")
    print("x is less than 5")
print("outside if")

In if
x is greater than 5
outside if


In [ ]:
x = 35
if x < 60:
    print("Grade A")
    
elif (x <= 50) or (x >= 40):                                #elif read as else-if
    print("Grade B")
else:
    print("Grade C")
print("I am outside if")

In [ ]:
x = -1
if x > 5:
    print("x is greater than 5")
elif x < 5:                                #elif read as else-if
    if x >=0:
        print("x is greater than 0")
        
        print("still in if")
        print("x is less than 5")
else:
    print("x is equal to 5")
print("I am outside if")

# And; Or operators

In [ ]:
x = 11
if ((x > 5) and  (x < 10)) and () or ():
    print("In if")
    print("x is greater than 5")
else:
    print("In else")
    print("x is less than 5")
print("outside if")

# Loop

In [ ]:
print("welcome")
print("welcome")
print("welcome")
print("welcome")
print("welcome")

In [ ]:
# Range function generates a list
# range(5) or range(0,5) generates a list [0,1,2,3,4]
range(2,5)

In [23]:
for y in range(5):
    print("Welcome")
    print(y)
    y = y+4
    print(y)
    
    
    
    
    #print("in for \n")
print(element)

Welcome
0
4
Welcome
1
5
Welcome
2
6
Welcome
3
7
Welcome
4
8


NameError: name 'element' is not defined

In [ ]:
for element in range(0,5,2): #[0,2,4]
    print(element)

In [ ]:
x=[8,6,4,3,1,9]

for i in x:
    print(i)
    if i == 4:
        pass
    else:
        print("no pass")
    print("after continue")    
print("outside loop")
    

In [ ]:
# break, continue, pass statements 

In [4]:
# While loop
x=0
y = 2

while x<5 + y :
    print(x)
    
    x = x + 2
    
    
    print("in while")
#x+=2

0
in while
2
in while
4
in while
6
in while


# Knowledge check

In [ ]:
# Debugging and increasing efficiency
'''
Fizzbuzz 
Write a program that prints the numbers 1-20, each on a new line
For each number that is a multiple of 3, print “Fizz” instead of the number
For each number that is a multiple of 5, print “Buzz” instead of the number
For each number that is a multiple of both 3 and 5, print “FizzBuzz” instead of the number
'''


In [ ]:
'''
Write a program to print the prime numbers upto 100
'''

In [ ]:
'''
Anagram
Write a function that takes two words as an argument and returns true if they are anagrams (contain the exact same letters)
and false otherwise.
'''

In [ ]:
'''
Write a function to print the string in reverse order
'''

text = "Welcome to Python"

In [ ]:
'''
Write function to print product of all the numbers from 1 to n i.e. n!
'''
n=7

In [ ]:
'''
Write function to print sum of all digits of number n
'''
n = 874

# Class and object

In [24]:
def test():
    print("in func")
    
test()

in func


In [25]:
class Batch():
    
    def intro(self):
        print("I am "+ self.name)
        

In [7]:
student1 = Batch()
student1.name = "Mike"
student1.intro()

I am Mike


In [8]:
student2 = Batch()
student2.name = "Tom"
#student2.age = 6
student2.intro()

I am Tom


In [9]:
intro()

NameError: name 'intro' is not defined

In [11]:
class Batch():
    def __init__(self, name, age):
        self.name = name
        self.age = age
    
    def intro(self, year_of_birth):
        print("I am "+ self.name)
        print("I am ", self.age)
        print(" I was born on", year_of_birth)



In [12]:
student1 = Batch("Mike",30)
student2 = Batch("Tom", 35)


In [13]:
student2.intro(1985)

I am Tom
I am  35
 I was born on 1985


In [ ]:
student = batch(arg1, arg2)

In [14]:
import numpy as np

In [19]:
# 1D numpy array
x=np.array([1,5,7,3,4,2,1,4])
print(type(x))
print(x.dtype)
print(x)
print("after array")

<class 'numpy.ndarray'>
int32
[1 5 7 3 4 2 1 4]
after array


In [16]:
# Difference between array and list
array_x = np.array([1,2,3])
array_y = np.array([4,5,6])
list_x = [1,2,3]
list_y = [4,5,6]

print(array_x + array_y)
print(list_x + list_y)

[5 7 9]
[1, 2, 3, 4, 5, 6]


In [22]:
# methods - mean, max, min; pi, multiplication, power - square
array_x.min()

1

In [24]:
np.pi
area = np.pi * 7 * 7
print(area)

153.93804002589985


In [25]:
# ND array
print([[1,1,1],[2,2,2],[3,3,3]])
x = np.array([[1,1,1],[2,2,2],[3,3,3]])
x

[[1, 1, 1], [2, 2, 2], [3, 3, 3]]


array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [30]:
x[2][2]

3

In [31]:
for element in x:
    print(element)

[1 1 1]
[2 2 2]
[3 3 3]
